version: '3'
services:
  child:
    build: child
    image: mmpc-child
    container_name: mmpc-child
    ports:
      - "1323:1323"
    depends_on:
      - root
  root:
    build: root
    image: mmpc-root
    container_name: mmpc-root
    ports:
      - "8545:8545"
